version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gocyclo
    - revive
  settings:
    gocyclo:
      min-complexity: 10
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
