// Code generated by MockGen. DO NOT EDIT.
// Source: modules/core/service/link_analyzer.go
//
// Generated by this command:
//
//	mockgen -source=modules/core/service/link_analyzer.go -destination=modules/core/internal/test/mocks/mock_link_analyzer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/nanda/doit/modules/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkAnalyzer is a mock of LinkAnalyzer interface.
type MockLinkAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockLinkAnalyzerMockRecorder
	isgomock struct{}
}

// MockLinkAnalyzerMockRecorder is the mock recorder for MockLinkAnalyzer.
type MockLinkAnalyzerMockRecorder struct {
	mock *MockLinkAnalyzer
}

// NewMockLinkAnalyzer creates a new mock instance.
func NewMockLinkAnalyzer(ctrl *gomock.Controller) *MockLinkAnalyzer {
	mock := &MockLinkAnalyzer{ctrl: ctrl}
	mock.recorder = &MockLinkAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkAnalyzer) EXPECT() *MockLinkAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockLinkAnalyzer) Analyze(ctx context.Context, shortCode string) (*entity.URLAnalytic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, shortCode)
	ret0, _ := ret[0].(*entity.URLAnalytic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockLinkAnalyzerMockRecorder) Analyze(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockLinkAnalyzer)(nil).Analyze), ctx, shortCode)
}
