// Code generated by MockGen. DO NOT EDIT.
// Source: modules/core/service/link_creator.go
//
// Generated by this command:
//
//	mockgen -source=modules/core/service/link_creator.go -destination=modules/core/internal/test/mocks/mock_link_creator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLinkCreator is a mock of LinkCreator interface.
type MockLinkCreator struct {
	ctrl     *gomock.Controller
	recorder *MockLinkCreatorMockRecorder
	isgomock struct{}
}

// MockLinkCreatorMockRecorder is the mock recorder for MockLinkCreator.
type MockLinkCreatorMockRecorder struct {
	mock *MockLinkCreator
}

// NewMockLinkCreator creates a new mock instance.
func NewMockLinkCreator(ctrl *gomock.Controller) *MockLinkCreator {
	mock := &MockLinkCreator{ctrl: ctrl}
	mock.recorder = &MockLinkCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkCreator) EXPECT() *MockLinkCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLinkCreator) Create(ctx context.Context, longURL string, ttlSeconds *int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, longURL, ttlSeconds)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLinkCreatorMockRecorder) Create(ctx, longURL, ttlSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkCreator)(nil).Create), ctx, longURL, ttlSeconds)
}
