// Code generated by MockGen. DO NOT EDIT.
// Source: modules/core/service/repository.go
//
// Generated by this command:
//
//	mockgen -source=modules/core/service/repository.go -destination=modules/core/internal/test/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/nanda/doit/modules/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockURLCacheRepo is a mock of URLCacheRepo interface.
type MockURLCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockURLCacheRepoMockRecorder
	isgomock struct{}
}

// MockURLCacheRepoMockRecorder is the mock recorder for MockURLCacheRepo.
type MockURLCacheRepoMockRecorder struct {
	mock *MockURLCacheRepo
}

// NewMockURLCacheRepo creates a new mock instance.
func NewMockURLCacheRepo(ctrl *gomock.Controller) *MockURLCacheRepo {
	mock := &MockURLCacheRepo{ctrl: ctrl}
	mock.recorder = &MockURLCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLCacheRepo) EXPECT() *MockURLCacheRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockURLCacheRepo) Create(ctx context.Context, longURL string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, longURL, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockURLCacheRepoMockRecorder) Create(ctx, longURL, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLCacheRepo)(nil).Create), ctx, longURL, ttl)
}

// Delete mocks base method.
func (m *MockURLCacheRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLCacheRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLCacheRepo)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockURLCacheRepo) Get(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLCacheRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLCacheRepo)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *MockURLCacheRepo) Set(ctx context.Context, id int64, longURL string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, id, longURL, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockURLCacheRepoMockRecorder) Set(ctx, id, longURL, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockURLCacheRepo)(nil).Set), ctx, id, longURL, ttl)
}

// MockURLAnalyticRepo is a mock of URLAnalyticRepo interface.
type MockURLAnalyticRepo struct {
	ctrl     *gomock.Controller
	recorder *MockURLAnalyticRepoMockRecorder
	isgomock struct{}
}

// MockURLAnalyticRepoMockRecorder is the mock recorder for MockURLAnalyticRepo.
type MockURLAnalyticRepoMockRecorder struct {
	mock *MockURLAnalyticRepo
}

// NewMockURLAnalyticRepo creates a new mock instance.
func NewMockURLAnalyticRepo(ctrl *gomock.Controller) *MockURLAnalyticRepo {
	mock := &MockURLAnalyticRepo{ctrl: ctrl}
	mock.recorder = &MockURLAnalyticRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLAnalyticRepo) EXPECT() *MockURLAnalyticRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockURLAnalyticRepo) Create(ctx context.Context, analytic *entity.URLAnalytic) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, analytic)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockURLAnalyticRepoMockRecorder) Create(ctx, analytic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLAnalyticRepo)(nil).Create), ctx, analytic)
}

// GetByURLID mocks base method.
func (m *MockURLAnalyticRepo) GetByURLID(ctx context.Context, urlID int64) (*entity.URLAnalytic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURLID", ctx, urlID)
	ret0, _ := ret[0].(*entity.URLAnalytic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURLID indicates an expected call of GetByURLID.
func (mr *MockURLAnalyticRepoMockRecorder) GetByURLID(ctx, urlID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURLID", reflect.TypeOf((*MockURLAnalyticRepo)(nil).GetByURLID), ctx, urlID)
}

// UpdateStat mocks base method.
func (m *MockURLAnalyticRepo) UpdateStat(ctx context.Context, urlID int64, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStat", ctx, urlID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStat indicates an expected call of UpdateStat.
func (mr *MockURLAnalyticRepoMockRecorder) UpdateStat(ctx, urlID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStat", reflect.TypeOf((*MockURLAnalyticRepo)(nil).UpdateStat), ctx, urlID, now)
}
