// Code generated by MockGen. DO NOT EDIT.
// Source: modules/core/service/link_redirector.go
//
// Generated by this command:
//
//	mockgen -source=modules/core/service/link_redirector.go -destination=modules/core/internal/test/mocks/mock_link_redirector.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLinkRedirector is a mock of LinkRedirector interface.
type MockLinkRedirector struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRedirectorMockRecorder
	isgomock struct{}
}

// MockLinkRedirectorMockRecorder is the mock recorder for MockLinkRedirector.
type MockLinkRedirectorMockRecorder struct {
	mock *MockLinkRedirector
}

// NewMockLinkRedirector creates a new mock instance.
func NewMockLinkRedirector(ctrl *gomock.Controller) *MockLinkRedirector {
	mock := &MockLinkRedirector{ctrl: ctrl}
	mock.recorder = &MockLinkRedirectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRedirector) EXPECT() *MockLinkRedirectorMockRecorder {
	return m.recorder
}

// Redirect mocks base method.
func (m *MockLinkRedirector) Redirect(ctx context.Context, shortCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redirect", ctx, shortCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Redirect indicates an expected call of Redirect.
func (mr *MockLinkRedirectorMockRecorder) Redirect(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockLinkRedirector)(nil).Redirect), ctx, shortCode)
}
